SELECT * FROM CustomerBehaviorTB

-- KPIs

SELECT COUNT(Customer_id) AS [Total Cutsomers] FROM CustomerBehaviorTB

SELECT SUM(Purchase_amount) AS [Total Revenue] FROM CustomerBehaviorTB

SELECT AVG(Purchase_amount) AS [Average Purchase Amount] FROM CustomerBehaviorTB

SELECT AVG(Review_rating) AS [Average Review Rating] FROM CustomerBehaviorTB

-- Business Questions
--Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender,SUM(purchase_amount) AS RevenueGenerated FROM CustomerBehaviorTB
GROUP BY Gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount FROM CustomerBehaviorTB
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM CustomerBehaviorTB)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased,ROUND(AVG(review_rating),1) AS AverageReviewRating FROM CustomerBehaviorTB
GROUP BY item_purchased

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,AVG(purchase_amount) AS AveragePurchaseAmount FROM CustomerBehaviorTB
WHERE shipping_type='Express' OR shipping_type='Standard'
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS AverageSpend,SUM(purchase_amount) AS TotalRevenue FROM CustomerBehaviorTB
GROUP BY subscription_status
ORDER BY TotalRevenue desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 Item_purchased,
CAST(ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS decimal(4,2)) AS DiscountRate 
FROM CustomerBehaviorTB
GROUP BY item_purchased
ORDER BY DiscountRate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM CustomerBehaviorTB)
SELECT customer_segment,count(*) AS [Number of Customers]
FROM customer_type 
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH ItemCounts AS (
    SELECT Category,
           Item_purchased,
           COUNT(customer_id) AS TotalOrders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ItemRank
    FROM CustomerBehaviorTB
    GROUP BY Category, Item_purchased
)
SELECT ItemRank,Category, Item_purchased, TotalOrders
FROM ItemCounts
WHERE ItemRank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT Subscription_status,COUNT(customer_id) AS RepeatBuyers
FROM CustomerBehaviorTB
WHERE previous_purchases > 5
GROUP BY Subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT Age_group,SUM(Purchase_amount) AS [Total Revenue]
FROM CustomerBehaviorTB
GROUP BY Age_group
ORDER BY [Total Revenue] DESC;