SELECT * FROM CustomerBehaviorTB

-- KPIs

SELECT COUNT(Customer_id) AS [Total Cutsomers] FROM CustomerBehaviorTB

SELECT SUM(Purchase_amount) AS [Total Revenue] FROM CustomerBehaviorTB

SELECT AVG(Purchase_amount) AS [Average Purchase Amount] FROM CustomerBehaviorTB

SELECT AVG(Review_rating) AS [Average Review Rating] FROM CustomerBehaviorTB

-- Business Questions
--Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender,SUM(purchase_amount) AS RevenueGenerated FROM CustomerBehaviorTB
GROUP BY Gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount FROM CustomerBehaviorTB
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM CustomerBehaviorTB)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased,ROUND(AVG(review_rating),1) AS AverageReviewRating FROM CustomerBehaviorTB
GROUP BY item_purchased

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,AVG(purchase_amount) AS AveragePurchaseAmount FROM CustomerBehaviorTB
WHERE shipping_type='Express' OR shipping_type='Standard'
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS AverageSpend,SUM(purchase_amount) AS TotalRevenue FROM CustomerBehaviorTB
GROUP BY subscription_status
ORDER BY TotalRevenue desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate 
FROM CustomerBehaviorTB
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM CustomerBehaviorTB)
select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM CustomerBehaviorTB
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM CustomerBehaviorTB
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM CustomerBehaviorTB
GROUP BY age_group
ORDER BY total_revenue desc;